const now = new Date();
console.log("Current date and time:", now);
console.log("Date as a string:", now.toDateString());
console.log("Date as an ISO string:", now.toISOString());
console.log("Date as a JSON string:", now.toJSON());
console.log("Date as a localized date string:", now.toLocaleDateString());
console.log("Date as a localized string:", now.toLocaleString());
console.log("Date as a localized time string:", now.toLocaleTimeString());
console.log("Date as a string:", now.toString());
console.log("Date as a time string:", now.toTimeString());
console.log("Date as a UTC string:", now.toUTCString());
